### ISSUE TITLE
Error when adding property values in "create mode"

### ISSUE THREAD

**Issue by marijorg** [Geta/geta-optimizely-genericlinks#7]
## How to reproduce

- Create new block
- Fill inn values for heading and add links
- Press 'Create'

Block will fail to be created and the following error can be retrieved from network tab:

> System.NotSupportedException: Specified method is not supported. The unsupported member type is located on type 'Geta.Optimizely.GenericLinks.LinkDataCollection`1[Skeidar.Web.Infrastructure.Properties.ThumbnailLinkData]'. Path: $[0] | LineNumber: 0 | BytePositionInLine: 2.
 ---> System.NotSupportedException: Specified method is not supported.
   at Geta.Optimizely.GenericLinks.Converters.Json.SystemTextLinkDataConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)

![image](https://user-images.githubusercontent.com/2111786/173059530-8a49ccbc-e671-44dd-b717-4282768b89ac.png)

**Comment by svenrog** [comment]
See if version `1.3.4` works better. I've added read functionality that will mitigate the error.
